server:
 port: 0

spring:
 application:
  name: customer-service
 datasource:
  url: jdbc:mysql://localhost:3306/customer?serverTimezone=Asia/Seoul
  username: root
  password: 1q2w3e4r!!
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true

eureka:
 client:
  serviceUrl:
   defaultZone: http://192.168.0.203:8761/eureka

 instance:
  instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  prefer-ip-address: true